import API from './api';
export const studentService = {
  getDashboard: async () => (await API.get('/student/dashboard')).data,
  getDocumentUploadConfig: async () => (await API.get('/student/documents/upload-config')).data,
  getDocuments: async (search = '') => (await API.get('/student/documents', { params: search ? { search } : {} })).data,
  getDocumentById: async (id) => (await API.get(`/student/documents/${id}`)).data,
  deleteDocument: async (id) => (await API.delete(`/student/documents/${id}`)).data,
  analyzeDocument: async (formData) => (await API.post('/student/documents/analyze', formData, {
    headers: { 'Content-Type': 'multipart/form-data' },
  })).data,
  askDocumentQuestion: async (id, question) => (await API.post(`/student/documents/${id}/chat`, { question })).data,
  submitGeneratedDocumentQuiz: async (id, answers) => (await API.post(`/student/documents/${id}/quiz/submit`, { answers })).data,
  getInstructorContent: async (params = {}) => (await API.get('/student/instructor-content', { params })).data,
  getProfile: async () => (await API.get('/student/profile')).data,
  updateProfile: async (payload) => (await API.put('/student/profile', payload)).data,
  getCourses: async () => (await API.get('/student/courses')).data,
  getCourseDetail: async (id) => (await API.get(`/student/courses/${id}`)).data,
  getLessonDetail: async (courseId, lessonIndex) => (await API.get(`/student/courses/${courseId}/lessons/${lessonIndex}`)).data,
  enrollCourse: async (id) => (await API.post(`/student/courses/${id}/enroll`)).data,
  payForCourse: async (id, payload = {}) => (await API.post(`/student/courses/${id}/pay`, payload)).data,
  confirmCoursePayment: async (id, sessionId) => (await API.post(`/student/courses/${id}/pay/confirm`, { sessionId })).data,
  completeLesson: async (courseId, lessonIndex, completed = true) => (await API.post(`/student/courses/${courseId}/lessons/${lessonIndex}/complete`, { completed })).data,
  getSubscription: async () => (await API.get('/student/subscription')).data,
  simulateSubscription: async (payload) => (await API.post('/student/subscription/simulate', payload)).data,
  generateStructuredContent: async (payload) => (await API.post('/student/generate-content', payload)).data,
  getFlashcards: async (courseId) => (await API.get('/student/flashcards', { params: courseId ? { courseId } : {} })).data,
  trackFlashcardReview: async (id) => (await API.post(`/student/flashcards/${id}/review`)).data,
  getQuizzes: async () => (await API.get('/student/quizzes')).data,
  submitQuiz: async (id, answers) => (await API.post(`/student/quizzes/${id}/submit`, { answers })).data,
  getAttempts: async () => (await API.get('/student/attempts')).data,
  getRecommendations: async () => (await API.get('/student/recommendations')).data,
  refreshRecommendations: async () => (await API.post('/student/recommendations/refresh')).data,
};
